runtime: go123
env: standard

handlers :
  - url: /static
    static_dir: static
  - url: /.*
    script: auto
    secure: always

libraries:
  - name: "firebase-admin"
    version: latest

resources:
  cpu: 1
  memory_gb: 1

